<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.6</Version>
    <ApplicationIcon>pos.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="pos.ico" />
  </ItemGroup>

<ItemGroup>
    <!-- Gives you ASP.NET Core hosting & minimal APIs -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>

<ItemGroup>
  <None Include=".github\workflows\release.yml" />
</ItemGroup>

<ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.5" />
    <PackageReference Include="Velopack" Version="0.0.*" />
</ItemGroup>

  <ItemGroup>
    <Reference Include="Interop.CoreScanner">
      <HintPath>lib\Interop.CoreScanner.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
    <Reference Include="POSLinkAdmin">
      <HintPath>PaxLibs\POSLinkAdmin.dll</HintPath>
    </Reference>
    <Reference Include="POSLinkCore">
      <HintPath>PaxLibs\POSLinkCore.dll</HintPath>
    </Reference>
    <Reference Include="POSLinkSemiIntegration">
      <HintPath>PaxLibs\POSLinkSemiIntegration.dll</HintPath>
    </Reference>
    <Reference Include="POSLinkUart">
      <HintPath>PaxLibs\POSLinkUart.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
